//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Logger
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ClaimStakerDEVEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ClaimStakerDEVEntities object using the connection string found in the 'ClaimStakerDEVEntities' section of the application configuration file.
        /// </summary>
        public ClaimStakerDEVEntities() : base("name=ClaimStakerDEVEntities", "ClaimStakerDEVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ClaimStakerDEVEntities object.
        /// </summary>
        public ClaimStakerDEVEntities(string connectionString) : base(connectionString, "ClaimStakerDEVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ClaimStakerDEVEntities object.
        /// </summary>
        public ClaimStakerDEVEntities(EntityConnection connection) : base(connection, "ClaimStakerDEVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Test> Tests
        {
            get
            {
                if ((_Tests == null))
                {
                    _Tests = base.CreateObjectSet<Test>("Tests");
                }
                return _Tests;
            }
        }
        private ObjectSet<Test> _Tests;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTests(Test test)
        {
            base.AddObject("Tests", test);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClaimStakerDEVModel", Name="Test")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Test : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Test object.
        /// </summary>
        /// <param name="logID">Initial value of the LogID property.</param>
        public static Test CreateTest(global::System.Int32 logID)
        {
            Test test = new Test();
            test.LogID = logID;
            return test;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LogID
        {
            get
            {
                return _LogID;
            }
            set
            {
                if (_LogID != value)
                {
                    OnLogIDChanging(value);
                    ReportPropertyChanging("LogID");
                    _LogID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LogID");
                    OnLogIDChanged();
                }
            }
        }
        private global::System.Int32 _LogID;
        partial void OnLogIDChanging(global::System.Int32 value);
        partial void OnLogIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreated_DT
        {
            get
            {
                return _DateCreated_DT;
            }
            set
            {
                OnDateCreated_DTChanging(value);
                ReportPropertyChanging("DateCreated_DT");
                _DateCreated_DT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated_DT");
                OnDateCreated_DTChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreated_DT;
        partial void OnDateCreated_DTChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreated_DTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message_VC
        {
            get
            {
                return _Message_VC;
            }
            set
            {
                OnMessage_VCChanging(value);
                ReportPropertyChanging("Message_VC");
                _Message_VC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message_VC");
                OnMessage_VCChanged();
            }
        }
        private global::System.String _Message_VC;
        partial void OnMessage_VCChanging(global::System.String value);
        partial void OnMessage_VCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExceptionThrower_VC
        {
            get
            {
                return _ExceptionThrower_VC;
            }
            set
            {
                OnExceptionThrower_VCChanging(value);
                ReportPropertyChanging("ExceptionThrower_VC");
                _ExceptionThrower_VC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExceptionThrower_VC");
                OnExceptionThrower_VCChanged();
            }
        }
        private global::System.String _ExceptionThrower_VC;
        partial void OnExceptionThrower_VCChanging(global::System.String value);
        partial void OnExceptionThrower_VCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LogLevel_VC
        {
            get
            {
                return _LogLevel_VC;
            }
            set
            {
                OnLogLevel_VCChanging(value);
                ReportPropertyChanging("LogLevel_VC");
                _LogLevel_VC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LogLevel_VC");
                OnLogLevel_VCChanged();
            }
        }
        private global::System.String _LogLevel_VC;
        partial void OnLogLevel_VCChanging(global::System.String value);
        partial void OnLogLevel_VCChanged();

        #endregion

    
    }

    #endregion

    
}
