//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ClaimStakerDEVModel", "FK_TestErrorLog_TestErrorLog", "TestLogs_T", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Logger.TestLogs_T), "TestErrorLog", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Logger.TestErrorLog), true)]

#endregion

namespace Logger
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ClaimStakerDEVEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ClaimStakerDEVEntities object using the connection string found in the 'ClaimStakerDEVEntities' section of the application configuration file.
        /// </summary>
        public ClaimStakerDEVEntities() : base("name=ClaimStakerDEVEntities", "ClaimStakerDEVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ClaimStakerDEVEntities object.
        /// </summary>
        public ClaimStakerDEVEntities(string connectionString) : base(connectionString, "ClaimStakerDEVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ClaimStakerDEVEntities object.
        /// </summary>
        public ClaimStakerDEVEntities(EntityConnection connection) : base(connection, "ClaimStakerDEVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TestErrorLog> TestErrorLogs
        {
            get
            {
                if ((_TestErrorLogs == null))
                {
                    _TestErrorLogs = base.CreateObjectSet<TestErrorLog>("TestErrorLogs");
                }
                return _TestErrorLogs;
            }
        }
        private ObjectSet<TestErrorLog> _TestErrorLogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TestLogs_T> TestLogs_T
        {
            get
            {
                if ((_TestLogs_T == null))
                {
                    _TestLogs_T = base.CreateObjectSet<TestLogs_T>("TestLogs_T");
                }
                return _TestLogs_T;
            }
        }
        private ObjectSet<TestLogs_T> _TestLogs_T;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TestErrorLogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTestErrorLogs(TestErrorLog testErrorLog)
        {
            base.AddObject("TestErrorLogs", testErrorLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TestLogs_T EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTestLogs_T(TestLogs_T testLogs_T)
        {
            base.AddObject("TestLogs_T", testLogs_T);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClaimStakerDEVModel", Name="TestErrorLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TestErrorLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TestErrorLog object.
        /// </summary>
        /// <param name="logID">Initial value of the LogID property.</param>
        public static TestErrorLog CreateTestErrorLog(global::System.Int32 logID)
        {
            TestErrorLog testErrorLog = new TestErrorLog();
            testErrorLog.LogID = logID;
            return testErrorLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LogID
        {
            get
            {
                return _LogID;
            }
            set
            {
                if (_LogID != value)
                {
                    OnLogIDChanging(value);
                    ReportPropertyChanging("LogID");
                    _LogID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LogID");
                    OnLogIDChanged();
                }
            }
        }
        private global::System.Int32 _LogID;
        partial void OnLogIDChanging(global::System.Int32 value);
        partial void OnLogIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreated_DT
        {
            get
            {
                return _DateCreated_DT;
            }
            set
            {
                OnDateCreated_DTChanging(value);
                ReportPropertyChanging("DateCreated_DT");
                _DateCreated_DT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated_DT");
                OnDateCreated_DTChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreated_DT;
        partial void OnDateCreated_DTChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreated_DTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message_VC
        {
            get
            {
                return _Message_VC;
            }
            set
            {
                OnMessage_VCChanging(value);
                ReportPropertyChanging("Message_VC");
                _Message_VC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message_VC");
                OnMessage_VCChanged();
            }
        }
        private global::System.String _Message_VC;
        partial void OnMessage_VCChanging(global::System.String value);
        partial void OnMessage_VCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExceptionThrower_VC
        {
            get
            {
                return _ExceptionThrower_VC;
            }
            set
            {
                OnExceptionThrower_VCChanging(value);
                ReportPropertyChanging("ExceptionThrower_VC");
                _ExceptionThrower_VC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExceptionThrower_VC");
                OnExceptionThrower_VCChanged();
            }
        }
        private global::System.String _ExceptionThrower_VC;
        partial void OnExceptionThrower_VCChanging(global::System.String value);
        partial void OnExceptionThrower_VCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LogLevel_VC
        {
            get
            {
                return _LogLevel_VC;
            }
            set
            {
                OnLogLevel_VCChanging(value);
                ReportPropertyChanging("LogLevel_VC");
                _LogLevel_VC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LogLevel_VC");
                OnLogLevel_VCChanged();
            }
        }
        private global::System.String _LogLevel_VC;
        partial void OnLogLevel_VCChanging(global::System.String value);
        partial void OnLogLevel_VCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TestLog_ID
        {
            get
            {
                return _TestLog_ID;
            }
            set
            {
                OnTestLog_IDChanging(value);
                ReportPropertyChanging("TestLog_ID");
                _TestLog_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TestLog_ID");
                OnTestLog_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _TestLog_ID;
        partial void OnTestLog_IDChanging(Nullable<global::System.Int64> value);
        partial void OnTestLog_IDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClaimStakerDEVModel", "FK_TestErrorLog_TestErrorLog", "TestLogs_T")]
        public TestLogs_T TestLogs_T
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TestLogs_T>("ClaimStakerDEVModel.FK_TestErrorLog_TestErrorLog", "TestLogs_T").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TestLogs_T>("ClaimStakerDEVModel.FK_TestErrorLog_TestErrorLog", "TestLogs_T").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TestLogs_T> TestLogs_TReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TestLogs_T>("ClaimStakerDEVModel.FK_TestErrorLog_TestErrorLog", "TestLogs_T");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TestLogs_T>("ClaimStakerDEVModel.FK_TestErrorLog_TestErrorLog", "TestLogs_T", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClaimStakerDEVModel", Name="TestLogs_T")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TestLogs_T : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TestLogs_T object.
        /// </summary>
        /// <param name="testLog_ID">Initial value of the TestLog_ID property.</param>
        public static TestLogs_T CreateTestLogs_T(global::System.Int64 testLog_ID)
        {
            TestLogs_T testLogs_T = new TestLogs_T();
            testLogs_T.TestLog_ID = testLog_ID;
            return testLogs_T;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TestLog_ID
        {
            get
            {
                return _TestLog_ID;
            }
            set
            {
                if (_TestLog_ID != value)
                {
                    OnTestLog_IDChanging(value);
                    ReportPropertyChanging("TestLog_ID");
                    _TestLog_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TestLog_ID");
                    OnTestLog_IDChanged();
                }
            }
        }
        private global::System.Int64 _TestLog_ID;
        partial void OnTestLog_IDChanging(global::System.Int64 value);
        partial void OnTestLog_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TestExecuted_VC
        {
            get
            {
                return _TestExecuted_VC;
            }
            set
            {
                OnTestExecuted_VCChanging(value);
                ReportPropertyChanging("TestExecuted_VC");
                _TestExecuted_VC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TestExecuted_VC");
                OnTestExecuted_VCChanged();
            }
        }
        private global::System.String _TestExecuted_VC;
        partial void OnTestExecuted_VCChanging(global::System.String value);
        partial void OnTestExecuted_VCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateExecuted_DT
        {
            get
            {
                return _DateExecuted_DT;
            }
            set
            {
                OnDateExecuted_DTChanging(value);
                ReportPropertyChanging("DateExecuted_DT");
                _DateExecuted_DT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateExecuted_DT");
                OnDateExecuted_DTChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateExecuted_DT;
        partial void OnDateExecuted_DTChanging(Nullable<global::System.DateTime> value);
        partial void OnDateExecuted_DTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes_VC
        {
            get
            {
                return _Notes_VC;
            }
            set
            {
                OnNotes_VCChanging(value);
                ReportPropertyChanging("Notes_VC");
                _Notes_VC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes_VC");
                OnNotes_VCChanged();
            }
        }
        private global::System.String _Notes_VC;
        partial void OnNotes_VCChanging(global::System.String value);
        partial void OnNotes_VCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> PassFail
        {
            get
            {
                return _PassFail;
            }
            set
            {
                OnPassFailChanging(value);
                ReportPropertyChanging("PassFail");
                _PassFail = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PassFail");
                OnPassFailChanged();
            }
        }
        private Nullable<global::System.Boolean> _PassFail;
        partial void OnPassFailChanging(Nullable<global::System.Boolean> value);
        partial void OnPassFailChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClaimStakerDEVModel", "FK_TestErrorLog_TestErrorLog", "TestErrorLog")]
        public EntityCollection<TestErrorLog> TestErrorLogs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TestErrorLog>("ClaimStakerDEVModel.FK_TestErrorLog_TestErrorLog", "TestErrorLog");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TestErrorLog>("ClaimStakerDEVModel.FK_TestErrorLog_TestErrorLog", "TestErrorLog", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
