#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatementsTesting
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ClaimStakerDEV")]
	public partial class StatementsDataModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertStatement_T(Statement_T instance);
    partial void UpdateStatement_T(Statement_T instance);
    partial void DeleteStatement_T(Statement_T instance);
    partial void InsertStatementLineItem_T(StatementLineItem_T instance);
    partial void UpdateStatementLineItem_T(StatementLineItem_T instance);
    partial void DeleteStatementLineItem_T(StatementLineItem_T instance);
    #endregion
		
		public StatementsDataModelDataContext() : 
				base(global::StatementsTesting.Properties.Settings.Default.ClaimStakerDEVConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StatementsDataModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StatementsDataModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StatementsDataModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StatementsDataModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Statement_T> Statement_Ts
		{
			get
			{
				return this.GetTable<Statement_T>();
			}
		}
		
		public System.Data.Linq.Table<StatementLineItem_T> StatementLineItem_Ts
		{
			get
			{
				return this.GetTable<StatementLineItem_T>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Statement_T")]
	public partial class Statement_T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Claim_ID;
		
		private long _Parent_ID;
		
		private System.DateTime _LastUpdate_DT;
		
		private int _Payer_ID;
		
		private int _Provider_ID;
		
		private string _BatchNum_VC;
		
		private string _ClientID_VC;
		
		private string _VendorClaimID_VC;
		
		private bool _IsDuplicateClaim_BT;
		
		private System.Nullable<System.DateTime> _ReportDate_DT;
		
		private System.Nullable<System.DateTime> _LastProcessDate_DT;
		
		private byte _ClaimStatus_TI;
		
		private bool _IsProcessNow_BT;
		
		private bool _IsDoNotProcess_BT;
		
		private bool _IsNoCharge_BT;
		
		private bool _IsNewDocClaim_BT;
		
		private string _Errors_CH;
		
		private byte _NumberOfClaims_TI;
		
		private int _OutputSub_ID;
		
		private string _Note_VC;
		
		private string _F01_RecipientAccountNumber_VC;
		
		private string _F02_RecipientLastName_VC;
		
		private string _F02_RecipientFirstName_VC;
		
		private string _F02_RecipientMI_VC;
		
		private string _F03A_RecipientAddress1_VC;
		
		private string _F03B_RecipientAddress2_VC;
		
		private string _F04_RecipientCity_VC;
		
		private string _F05_RecipientST_VC;
		
		private string _F06_RecipientZip_VC;
		
		private string _F51_PatientLastName_VC;
		
		private string _F51_PatientFirstName_VC;
		
		private string _F51_PatientMI_VC;
		
		private string _F07_OfficeName_VC;
		
		private string _F08A_OfficeAddress1_VC;
		
		private string _F08B_OfficeAddress2_VC;
		
		private string _F09_OfficeCity_VC;
		
		private string _F10_OfficeST_VC;
		
		private string _F11_OfficeZip_VC;
		
		private string _F12_OfficePhone_VC;
		
		private string _F13_PatientAccountNumber_VC;
		
		private string _F14_StatementDate_VC;
		
		private string _F15_PageNumber_VC;
		
		private string _F16_RemitToName_VC;
		
		private string _F17_RemitToAddress1_VC;
		
		private string _F18_RemitToAddress2_VC;
		
		private string _F19_RemitToCity_VC;
		
		private string _F20_RemitToST_VC;
		
		private string _F21_RemitToZip_VC;
		
		private string _F22_RemitToPhone_VC;
		
		private string _F23_RenderingProviderLastName_VC;
		
		private string _F23_RenderingProviderFirstName_VC;
		
		private string _F23_RenderingProviderMI_VC;
		
		private string _F24_RenderingProviderID_VC;
		
		private string _F25_RenderingProviderST_VC;
		
		private string _F26_PriorStatementDate_VC;
		
		private string _F27_PaymentDueDate_VC;
		
		private string _F28_PriorBalance_VC;
		
		private string _F29_Adjustments_VC;
		
		private string _F30_BalanceDue_VC;
		
		private string _F30B_AccountBalance_VC;
		
		private string _F31_FinanceCharge_VC;
		
		private string _F32_Credits_VC;
		
		private string _F33_EstimatedInsurancePayment_VC;
		
		private string _F34_PatientShare_VC;
		
		private string _F35_CurrentBalance_VC;
		
		private string _F36_PastDue30_VC;
		
		private string _F37_PastDue60_VC;
		
		private string _F38_PastDue90_VC;
		
		private string _F39_PastDue120_VC;
		
		private string _TopNote_VC;
		
		private string _F40_Notes1_VC;
		
		private string _F41_Notes2_VC;
		
		private string _F42_Notes3_VC;
		
		private string _F43_Notes4_VC;
		
		private string _F44_Notes5_VC;
		
		private string _F45_Notes6_VC;
		
		private string _F46_Notes7_VC;
		
		private string _F47_Notes8_VC;
		
		private string _F48_Notes9_VC;
		
		private string _F49_Notes10_VC;
		
		private string _F00_StatementTitle_VC;
		
		private string _F50_PendingAtInsurance_VC;
		
		private string _ServiceDate_VC;
		
		private string _UniqueNameOnClaim_VC;
		
		private System.Nullable<int> _Vendor_ID;
		
		private System.Nullable<int> _OriginalDocumentPageCount;
		
		private string _OriginalDocumentName;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _RenderingProviderNameSuffix;
		
		private string _BillingContactFirstName;
		
		private string _BillingContactMiddleName;
		
		private string _BillingContactLastName;
		
		private string _BillingContactSuffix;
		
		private string _RecipientNameSuffix;
		
		private string _PatientNameSuffix;
		
		private System.Nullable<int> _DocumentSource;
		
		private EntitySet<StatementLineItem_T> _StatementLineItem_Ts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClaim_IDChanging(long value);
    partial void OnClaim_IDChanged();
    partial void OnParent_IDChanging(long value);
    partial void OnParent_IDChanged();
    partial void OnLastUpdate_DTChanging(System.DateTime value);
    partial void OnLastUpdate_DTChanged();
    partial void OnPayer_IDChanging(int value);
    partial void OnPayer_IDChanged();
    partial void OnProvider_IDChanging(int value);
    partial void OnProvider_IDChanged();
    partial void OnBatchNum_VCChanging(string value);
    partial void OnBatchNum_VCChanged();
    partial void OnClientID_VCChanging(string value);
    partial void OnClientID_VCChanged();
    partial void OnVendorClaimID_VCChanging(string value);
    partial void OnVendorClaimID_VCChanged();
    partial void OnIsDuplicateClaim_BTChanging(bool value);
    partial void OnIsDuplicateClaim_BTChanged();
    partial void OnReportDate_DTChanging(System.Nullable<System.DateTime> value);
    partial void OnReportDate_DTChanged();
    partial void OnLastProcessDate_DTChanging(System.Nullable<System.DateTime> value);
    partial void OnLastProcessDate_DTChanged();
    partial void OnClaimStatus_TIChanging(byte value);
    partial void OnClaimStatus_TIChanged();
    partial void OnIsProcessNow_BTChanging(bool value);
    partial void OnIsProcessNow_BTChanged();
    partial void OnIsDoNotProcess_BTChanging(bool value);
    partial void OnIsDoNotProcess_BTChanged();
    partial void OnIsNoCharge_BTChanging(bool value);
    partial void OnIsNoCharge_BTChanged();
    partial void OnIsNewDocClaim_BTChanging(bool value);
    partial void OnIsNewDocClaim_BTChanged();
    partial void OnErrors_CHChanging(string value);
    partial void OnErrors_CHChanged();
    partial void OnNumberOfClaims_TIChanging(byte value);
    partial void OnNumberOfClaims_TIChanged();
    partial void OnOutputSub_IDChanging(int value);
    partial void OnOutputSub_IDChanged();
    partial void OnNote_VCChanging(string value);
    partial void OnNote_VCChanged();
    partial void OnF01_RecipientAccountNumber_VCChanging(string value);
    partial void OnF01_RecipientAccountNumber_VCChanged();
    partial void OnF02_RecipientLastName_VCChanging(string value);
    partial void OnF02_RecipientLastName_VCChanged();
    partial void OnF02_RecipientFirstName_VCChanging(string value);
    partial void OnF02_RecipientFirstName_VCChanged();
    partial void OnF02_RecipientMI_VCChanging(string value);
    partial void OnF02_RecipientMI_VCChanged();
    partial void OnF03A_RecipientAddress1_VCChanging(string value);
    partial void OnF03A_RecipientAddress1_VCChanged();
    partial void OnF03B_RecipientAddress2_VCChanging(string value);
    partial void OnF03B_RecipientAddress2_VCChanged();
    partial void OnF04_RecipientCity_VCChanging(string value);
    partial void OnF04_RecipientCity_VCChanged();
    partial void OnF05_RecipientST_VCChanging(string value);
    partial void OnF05_RecipientST_VCChanged();
    partial void OnF06_RecipientZip_VCChanging(string value);
    partial void OnF06_RecipientZip_VCChanged();
    partial void OnF51_PatientLastName_VCChanging(string value);
    partial void OnF51_PatientLastName_VCChanged();
    partial void OnF51_PatientFirstName_VCChanging(string value);
    partial void OnF51_PatientFirstName_VCChanged();
    partial void OnF51_PatientMI_VCChanging(string value);
    partial void OnF51_PatientMI_VCChanged();
    partial void OnF07_OfficeName_VCChanging(string value);
    partial void OnF07_OfficeName_VCChanged();
    partial void OnF08A_OfficeAddress1_VCChanging(string value);
    partial void OnF08A_OfficeAddress1_VCChanged();
    partial void OnF08B_OfficeAddress2_VCChanging(string value);
    partial void OnF08B_OfficeAddress2_VCChanged();
    partial void OnF09_OfficeCity_VCChanging(string value);
    partial void OnF09_OfficeCity_VCChanged();
    partial void OnF10_OfficeST_VCChanging(string value);
    partial void OnF10_OfficeST_VCChanged();
    partial void OnF11_OfficeZip_VCChanging(string value);
    partial void OnF11_OfficeZip_VCChanged();
    partial void OnF12_OfficePhone_VCChanging(string value);
    partial void OnF12_OfficePhone_VCChanged();
    partial void OnF13_PatientAccountNumber_VCChanging(string value);
    partial void OnF13_PatientAccountNumber_VCChanged();
    partial void OnF14_StatementDate_VCChanging(string value);
    partial void OnF14_StatementDate_VCChanged();
    partial void OnF15_PageNumber_VCChanging(string value);
    partial void OnF15_PageNumber_VCChanged();
    partial void OnF16_RemitToName_VCChanging(string value);
    partial void OnF16_RemitToName_VCChanged();
    partial void OnF17_RemitToAddress1_VCChanging(string value);
    partial void OnF17_RemitToAddress1_VCChanged();
    partial void OnF18_RemitToAddress2_VCChanging(string value);
    partial void OnF18_RemitToAddress2_VCChanged();
    partial void OnF19_RemitToCity_VCChanging(string value);
    partial void OnF19_RemitToCity_VCChanged();
    partial void OnF20_RemitToST_VCChanging(string value);
    partial void OnF20_RemitToST_VCChanged();
    partial void OnF21_RemitToZip_VCChanging(string value);
    partial void OnF21_RemitToZip_VCChanged();
    partial void OnF22_RemitToPhone_VCChanging(string value);
    partial void OnF22_RemitToPhone_VCChanged();
    partial void OnF23_RenderingProviderLastName_VCChanging(string value);
    partial void OnF23_RenderingProviderLastName_VCChanged();
    partial void OnF23_RenderingProviderFirstName_VCChanging(string value);
    partial void OnF23_RenderingProviderFirstName_VCChanged();
    partial void OnF23_RenderingProviderMI_VCChanging(string value);
    partial void OnF23_RenderingProviderMI_VCChanged();
    partial void OnF24_RenderingProviderID_VCChanging(string value);
    partial void OnF24_RenderingProviderID_VCChanged();
    partial void OnF25_RenderingProviderST_VCChanging(string value);
    partial void OnF25_RenderingProviderST_VCChanged();
    partial void OnF26_PriorStatementDate_VCChanging(string value);
    partial void OnF26_PriorStatementDate_VCChanged();
    partial void OnF27_PaymentDueDate_VCChanging(string value);
    partial void OnF27_PaymentDueDate_VCChanged();
    partial void OnF28_PriorBalance_VCChanging(string value);
    partial void OnF28_PriorBalance_VCChanged();
    partial void OnF29_Adjustments_VCChanging(string value);
    partial void OnF29_Adjustments_VCChanged();
    partial void OnF30_BalanceDue_VCChanging(string value);
    partial void OnF30_BalanceDue_VCChanged();
    partial void OnF30B_AccountBalance_VCChanging(string value);
    partial void OnF30B_AccountBalance_VCChanged();
    partial void OnF31_FinanceCharge_VCChanging(string value);
    partial void OnF31_FinanceCharge_VCChanged();
    partial void OnF32_Credits_VCChanging(string value);
    partial void OnF32_Credits_VCChanged();
    partial void OnF33_EstimatedInsurancePayment_VCChanging(string value);
    partial void OnF33_EstimatedInsurancePayment_VCChanged();
    partial void OnF34_PatientShare_VCChanging(string value);
    partial void OnF34_PatientShare_VCChanged();
    partial void OnF35_CurrentBalance_VCChanging(string value);
    partial void OnF35_CurrentBalance_VCChanged();
    partial void OnF36_PastDue30_VCChanging(string value);
    partial void OnF36_PastDue30_VCChanged();
    partial void OnF37_PastDue60_VCChanging(string value);
    partial void OnF37_PastDue60_VCChanged();
    partial void OnF38_PastDue90_VCChanging(string value);
    partial void OnF38_PastDue90_VCChanged();
    partial void OnF39_PastDue120_VCChanging(string value);
    partial void OnF39_PastDue120_VCChanged();
    partial void OnTopNote_VCChanging(string value);
    partial void OnTopNote_VCChanged();
    partial void OnF40_Notes1_VCChanging(string value);
    partial void OnF40_Notes1_VCChanged();
    partial void OnF41_Notes2_VCChanging(string value);
    partial void OnF41_Notes2_VCChanged();
    partial void OnF42_Notes3_VCChanging(string value);
    partial void OnF42_Notes3_VCChanged();
    partial void OnF43_Notes4_VCChanging(string value);
    partial void OnF43_Notes4_VCChanged();
    partial void OnF44_Notes5_VCChanging(string value);
    partial void OnF44_Notes5_VCChanged();
    partial void OnF45_Notes6_VCChanging(string value);
    partial void OnF45_Notes6_VCChanged();
    partial void OnF46_Notes7_VCChanging(string value);
    partial void OnF46_Notes7_VCChanged();
    partial void OnF47_Notes8_VCChanging(string value);
    partial void OnF47_Notes8_VCChanged();
    partial void OnF48_Notes9_VCChanging(string value);
    partial void OnF48_Notes9_VCChanged();
    partial void OnF49_Notes10_VCChanging(string value);
    partial void OnF49_Notes10_VCChanged();
    partial void OnF00_StatementTitle_VCChanging(string value);
    partial void OnF00_StatementTitle_VCChanged();
    partial void OnF50_PendingAtInsurance_VCChanging(string value);
    partial void OnF50_PendingAtInsurance_VCChanged();
    partial void OnServiceDate_VCChanging(string value);
    partial void OnServiceDate_VCChanged();
    partial void OnUniqueNameOnClaim_VCChanging(string value);
    partial void OnUniqueNameOnClaim_VCChanged();
    partial void OnVendor_IDChanging(System.Nullable<int> value);
    partial void OnVendor_IDChanged();
    partial void OnOriginalDocumentPageCountChanging(System.Nullable<int> value);
    partial void OnOriginalDocumentPageCountChanged();
    partial void OnOriginalDocumentNameChanging(string value);
    partial void OnOriginalDocumentNameChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnRenderingProviderNameSuffixChanging(string value);
    partial void OnRenderingProviderNameSuffixChanged();
    partial void OnBillingContactFirstNameChanging(string value);
    partial void OnBillingContactFirstNameChanged();
    partial void OnBillingContactMiddleNameChanging(string value);
    partial void OnBillingContactMiddleNameChanged();
    partial void OnBillingContactLastNameChanging(string value);
    partial void OnBillingContactLastNameChanged();
    partial void OnBillingContactSuffixChanging(string value);
    partial void OnBillingContactSuffixChanged();
    partial void OnRecipientNameSuffixChanging(string value);
    partial void OnRecipientNameSuffixChanged();
    partial void OnPatientNameSuffixChanging(string value);
    partial void OnPatientNameSuffixChanged();
    partial void OnDocumentSourceChanging(System.Nullable<int> value);
    partial void OnDocumentSourceChanged();
    #endregion
		
		public Statement_T()
		{
			this._StatementLineItem_Ts = new EntitySet<StatementLineItem_T>(new Action<StatementLineItem_T>(this.attach_StatementLineItem_Ts), new Action<StatementLineItem_T>(this.detach_StatementLineItem_Ts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Claim_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Claim_ID
		{
			get
			{
				return this._Claim_ID;
			}
			set
			{
				if ((this._Claim_ID != value))
				{
					this.OnClaim_IDChanging(value);
					this.SendPropertyChanging();
					this._Claim_ID = value;
					this.SendPropertyChanged("Claim_ID");
					this.OnClaim_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent_ID", DbType="BigInt NOT NULL")]
		public long Parent_ID
		{
			get
			{
				return this._Parent_ID;
			}
			set
			{
				if ((this._Parent_ID != value))
				{
					this.OnParent_IDChanging(value);
					this.SendPropertyChanging();
					this._Parent_ID = value;
					this.SendPropertyChanged("Parent_ID");
					this.OnParent_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate_DT", DbType="DateTime NOT NULL")]
		public System.DateTime LastUpdate_DT
		{
			get
			{
				return this._LastUpdate_DT;
			}
			set
			{
				if ((this._LastUpdate_DT != value))
				{
					this.OnLastUpdate_DTChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate_DT = value;
					this.SendPropertyChanged("LastUpdate_DT");
					this.OnLastUpdate_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payer_ID", DbType="Int NOT NULL")]
		public int Payer_ID
		{
			get
			{
				return this._Payer_ID;
			}
			set
			{
				if ((this._Payer_ID != value))
				{
					this.OnPayer_IDChanging(value);
					this.SendPropertyChanging();
					this._Payer_ID = value;
					this.SendPropertyChanged("Payer_ID");
					this.OnPayer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provider_ID", DbType="Int NOT NULL")]
		public int Provider_ID
		{
			get
			{
				return this._Provider_ID;
			}
			set
			{
				if ((this._Provider_ID != value))
				{
					this.OnProvider_IDChanging(value);
					this.SendPropertyChanging();
					this._Provider_ID = value;
					this.SendPropertyChanged("Provider_ID");
					this.OnProvider_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatchNum_VC", DbType="VarChar(14) NOT NULL", CanBeNull=false)]
		public string BatchNum_VC
		{
			get
			{
				return this._BatchNum_VC;
			}
			set
			{
				if ((this._BatchNum_VC != value))
				{
					this.OnBatchNum_VCChanging(value);
					this.SendPropertyChanging();
					this._BatchNum_VC = value;
					this.SendPropertyChanged("BatchNum_VC");
					this.OnBatchNum_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID_VC", DbType="VarChar(3)")]
		public string ClientID_VC
		{
			get
			{
				return this._ClientID_VC;
			}
			set
			{
				if ((this._ClientID_VC != value))
				{
					this.OnClientID_VCChanging(value);
					this.SendPropertyChanging();
					this._ClientID_VC = value;
					this.SendPropertyChanged("ClientID_VC");
					this.OnClientID_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorClaimID_VC", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string VendorClaimID_VC
		{
			get
			{
				return this._VendorClaimID_VC;
			}
			set
			{
				if ((this._VendorClaimID_VC != value))
				{
					this.OnVendorClaimID_VCChanging(value);
					this.SendPropertyChanging();
					this._VendorClaimID_VC = value;
					this.SendPropertyChanged("VendorClaimID_VC");
					this.OnVendorClaimID_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDuplicateClaim_BT", DbType="Bit NOT NULL")]
		public bool IsDuplicateClaim_BT
		{
			get
			{
				return this._IsDuplicateClaim_BT;
			}
			set
			{
				if ((this._IsDuplicateClaim_BT != value))
				{
					this.OnIsDuplicateClaim_BTChanging(value);
					this.SendPropertyChanging();
					this._IsDuplicateClaim_BT = value;
					this.SendPropertyChanged("IsDuplicateClaim_BT");
					this.OnIsDuplicateClaim_BTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportDate_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> ReportDate_DT
		{
			get
			{
				return this._ReportDate_DT;
			}
			set
			{
				if ((this._ReportDate_DT != value))
				{
					this.OnReportDate_DTChanging(value);
					this.SendPropertyChanging();
					this._ReportDate_DT = value;
					this.SendPropertyChanged("ReportDate_DT");
					this.OnReportDate_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastProcessDate_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastProcessDate_DT
		{
			get
			{
				return this._LastProcessDate_DT;
			}
			set
			{
				if ((this._LastProcessDate_DT != value))
				{
					this.OnLastProcessDate_DTChanging(value);
					this.SendPropertyChanging();
					this._LastProcessDate_DT = value;
					this.SendPropertyChanged("LastProcessDate_DT");
					this.OnLastProcessDate_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaimStatus_TI", DbType="TinyInt NOT NULL")]
		public byte ClaimStatus_TI
		{
			get
			{
				return this._ClaimStatus_TI;
			}
			set
			{
				if ((this._ClaimStatus_TI != value))
				{
					this.OnClaimStatus_TIChanging(value);
					this.SendPropertyChanging();
					this._ClaimStatus_TI = value;
					this.SendPropertyChanged("ClaimStatus_TI");
					this.OnClaimStatus_TIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsProcessNow_BT", DbType="Bit NOT NULL")]
		public bool IsProcessNow_BT
		{
			get
			{
				return this._IsProcessNow_BT;
			}
			set
			{
				if ((this._IsProcessNow_BT != value))
				{
					this.OnIsProcessNow_BTChanging(value);
					this.SendPropertyChanging();
					this._IsProcessNow_BT = value;
					this.SendPropertyChanged("IsProcessNow_BT");
					this.OnIsProcessNow_BTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDoNotProcess_BT", DbType="Bit NOT NULL")]
		public bool IsDoNotProcess_BT
		{
			get
			{
				return this._IsDoNotProcess_BT;
			}
			set
			{
				if ((this._IsDoNotProcess_BT != value))
				{
					this.OnIsDoNotProcess_BTChanging(value);
					this.SendPropertyChanging();
					this._IsDoNotProcess_BT = value;
					this.SendPropertyChanged("IsDoNotProcess_BT");
					this.OnIsDoNotProcess_BTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNoCharge_BT", DbType="Bit NOT NULL")]
		public bool IsNoCharge_BT
		{
			get
			{
				return this._IsNoCharge_BT;
			}
			set
			{
				if ((this._IsNoCharge_BT != value))
				{
					this.OnIsNoCharge_BTChanging(value);
					this.SendPropertyChanging();
					this._IsNoCharge_BT = value;
					this.SendPropertyChanged("IsNoCharge_BT");
					this.OnIsNoCharge_BTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNewDocClaim_BT", DbType="Bit NOT NULL")]
		public bool IsNewDocClaim_BT
		{
			get
			{
				return this._IsNewDocClaim_BT;
			}
			set
			{
				if ((this._IsNewDocClaim_BT != value))
				{
					this.OnIsNewDocClaim_BTChanging(value);
					this.SendPropertyChanging();
					this._IsNewDocClaim_BT = value;
					this.SendPropertyChanged("IsNewDocClaim_BT");
					this.OnIsNewDocClaim_BTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Errors_CH", DbType="Char(225) NOT NULL", CanBeNull=false)]
		public string Errors_CH
		{
			get
			{
				return this._Errors_CH;
			}
			set
			{
				if ((this._Errors_CH != value))
				{
					this.OnErrors_CHChanging(value);
					this.SendPropertyChanging();
					this._Errors_CH = value;
					this.SendPropertyChanged("Errors_CH");
					this.OnErrors_CHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfClaims_TI", DbType="TinyInt NOT NULL")]
		public byte NumberOfClaims_TI
		{
			get
			{
				return this._NumberOfClaims_TI;
			}
			set
			{
				if ((this._NumberOfClaims_TI != value))
				{
					this.OnNumberOfClaims_TIChanging(value);
					this.SendPropertyChanging();
					this._NumberOfClaims_TI = value;
					this.SendPropertyChanged("NumberOfClaims_TI");
					this.OnNumberOfClaims_TIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutputSub_ID", DbType="Int NOT NULL")]
		public int OutputSub_ID
		{
			get
			{
				return this._OutputSub_ID;
			}
			set
			{
				if ((this._OutputSub_ID != value))
				{
					this.OnOutputSub_IDChanging(value);
					this.SendPropertyChanging();
					this._OutputSub_ID = value;
					this.SendPropertyChanged("OutputSub_ID");
					this.OnOutputSub_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note_VC", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Note_VC
		{
			get
			{
				return this._Note_VC;
			}
			set
			{
				if ((this._Note_VC != value))
				{
					this.OnNote_VCChanging(value);
					this.SendPropertyChanging();
					this._Note_VC = value;
					this.SendPropertyChanged("Note_VC");
					this.OnNote_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F01_RecipientAccountNumber_VC", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string F01_RecipientAccountNumber_VC
		{
			get
			{
				return this._F01_RecipientAccountNumber_VC;
			}
			set
			{
				if ((this._F01_RecipientAccountNumber_VC != value))
				{
					this.OnF01_RecipientAccountNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._F01_RecipientAccountNumber_VC = value;
					this.SendPropertyChanged("F01_RecipientAccountNumber_VC");
					this.OnF01_RecipientAccountNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F02_RecipientLastName_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string F02_RecipientLastName_VC
		{
			get
			{
				return this._F02_RecipientLastName_VC;
			}
			set
			{
				if ((this._F02_RecipientLastName_VC != value))
				{
					this.OnF02_RecipientLastName_VCChanging(value);
					this.SendPropertyChanging();
					this._F02_RecipientLastName_VC = value;
					this.SendPropertyChanged("F02_RecipientLastName_VC");
					this.OnF02_RecipientLastName_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F02_RecipientFirstName_VC", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string F02_RecipientFirstName_VC
		{
			get
			{
				return this._F02_RecipientFirstName_VC;
			}
			set
			{
				if ((this._F02_RecipientFirstName_VC != value))
				{
					this.OnF02_RecipientFirstName_VCChanging(value);
					this.SendPropertyChanging();
					this._F02_RecipientFirstName_VC = value;
					this.SendPropertyChanged("F02_RecipientFirstName_VC");
					this.OnF02_RecipientFirstName_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F02_RecipientMI_VC", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string F02_RecipientMI_VC
		{
			get
			{
				return this._F02_RecipientMI_VC;
			}
			set
			{
				if ((this._F02_RecipientMI_VC != value))
				{
					this.OnF02_RecipientMI_VCChanging(value);
					this.SendPropertyChanging();
					this._F02_RecipientMI_VC = value;
					this.SendPropertyChanged("F02_RecipientMI_VC");
					this.OnF02_RecipientMI_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F03A_RecipientAddress1_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string F03A_RecipientAddress1_VC
		{
			get
			{
				return this._F03A_RecipientAddress1_VC;
			}
			set
			{
				if ((this._F03A_RecipientAddress1_VC != value))
				{
					this.OnF03A_RecipientAddress1_VCChanging(value);
					this.SendPropertyChanging();
					this._F03A_RecipientAddress1_VC = value;
					this.SendPropertyChanged("F03A_RecipientAddress1_VC");
					this.OnF03A_RecipientAddress1_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F03B_RecipientAddress2_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string F03B_RecipientAddress2_VC
		{
			get
			{
				return this._F03B_RecipientAddress2_VC;
			}
			set
			{
				if ((this._F03B_RecipientAddress2_VC != value))
				{
					this.OnF03B_RecipientAddress2_VCChanging(value);
					this.SendPropertyChanging();
					this._F03B_RecipientAddress2_VC = value;
					this.SendPropertyChanged("F03B_RecipientAddress2_VC");
					this.OnF03B_RecipientAddress2_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F04_RecipientCity_VC", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string F04_RecipientCity_VC
		{
			get
			{
				return this._F04_RecipientCity_VC;
			}
			set
			{
				if ((this._F04_RecipientCity_VC != value))
				{
					this.OnF04_RecipientCity_VCChanging(value);
					this.SendPropertyChanging();
					this._F04_RecipientCity_VC = value;
					this.SendPropertyChanged("F04_RecipientCity_VC");
					this.OnF04_RecipientCity_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F05_RecipientST_VC", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string F05_RecipientST_VC
		{
			get
			{
				return this._F05_RecipientST_VC;
			}
			set
			{
				if ((this._F05_RecipientST_VC != value))
				{
					this.OnF05_RecipientST_VCChanging(value);
					this.SendPropertyChanging();
					this._F05_RecipientST_VC = value;
					this.SendPropertyChanged("F05_RecipientST_VC");
					this.OnF05_RecipientST_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F06_RecipientZip_VC", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string F06_RecipientZip_VC
		{
			get
			{
				return this._F06_RecipientZip_VC;
			}
			set
			{
				if ((this._F06_RecipientZip_VC != value))
				{
					this.OnF06_RecipientZip_VCChanging(value);
					this.SendPropertyChanging();
					this._F06_RecipientZip_VC = value;
					this.SendPropertyChanged("F06_RecipientZip_VC");
					this.OnF06_RecipientZip_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F51_PatientLastName_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string F51_PatientLastName_VC
		{
			get
			{
				return this._F51_PatientLastName_VC;
			}
			set
			{
				if ((this._F51_PatientLastName_VC != value))
				{
					this.OnF51_PatientLastName_VCChanging(value);
					this.SendPropertyChanging();
					this._F51_PatientLastName_VC = value;
					this.SendPropertyChanged("F51_PatientLastName_VC");
					this.OnF51_PatientLastName_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F51_PatientFirstName_VC", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string F51_PatientFirstName_VC
		{
			get
			{
				return this._F51_PatientFirstName_VC;
			}
			set
			{
				if ((this._F51_PatientFirstName_VC != value))
				{
					this.OnF51_PatientFirstName_VCChanging(value);
					this.SendPropertyChanging();
					this._F51_PatientFirstName_VC = value;
					this.SendPropertyChanged("F51_PatientFirstName_VC");
					this.OnF51_PatientFirstName_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F51_PatientMI_VC", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string F51_PatientMI_VC
		{
			get
			{
				return this._F51_PatientMI_VC;
			}
			set
			{
				if ((this._F51_PatientMI_VC != value))
				{
					this.OnF51_PatientMI_VCChanging(value);
					this.SendPropertyChanging();
					this._F51_PatientMI_VC = value;
					this.SendPropertyChanged("F51_PatientMI_VC");
					this.OnF51_PatientMI_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F07_OfficeName_VC", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string F07_OfficeName_VC
		{
			get
			{
				return this._F07_OfficeName_VC;
			}
			set
			{
				if ((this._F07_OfficeName_VC != value))
				{
					this.OnF07_OfficeName_VCChanging(value);
					this.SendPropertyChanging();
					this._F07_OfficeName_VC = value;
					this.SendPropertyChanged("F07_OfficeName_VC");
					this.OnF07_OfficeName_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F08A_OfficeAddress1_VC", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string F08A_OfficeAddress1_VC
		{
			get
			{
				return this._F08A_OfficeAddress1_VC;
			}
			set
			{
				if ((this._F08A_OfficeAddress1_VC != value))
				{
					this.OnF08A_OfficeAddress1_VCChanging(value);
					this.SendPropertyChanging();
					this._F08A_OfficeAddress1_VC = value;
					this.SendPropertyChanged("F08A_OfficeAddress1_VC");
					this.OnF08A_OfficeAddress1_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F08B_OfficeAddress2_VC", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string F08B_OfficeAddress2_VC
		{
			get
			{
				return this._F08B_OfficeAddress2_VC;
			}
			set
			{
				if ((this._F08B_OfficeAddress2_VC != value))
				{
					this.OnF08B_OfficeAddress2_VCChanging(value);
					this.SendPropertyChanging();
					this._F08B_OfficeAddress2_VC = value;
					this.SendPropertyChanged("F08B_OfficeAddress2_VC");
					this.OnF08B_OfficeAddress2_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F09_OfficeCity_VC", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string F09_OfficeCity_VC
		{
			get
			{
				return this._F09_OfficeCity_VC;
			}
			set
			{
				if ((this._F09_OfficeCity_VC != value))
				{
					this.OnF09_OfficeCity_VCChanging(value);
					this.SendPropertyChanging();
					this._F09_OfficeCity_VC = value;
					this.SendPropertyChanged("F09_OfficeCity_VC");
					this.OnF09_OfficeCity_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F10_OfficeST_VC", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string F10_OfficeST_VC
		{
			get
			{
				return this._F10_OfficeST_VC;
			}
			set
			{
				if ((this._F10_OfficeST_VC != value))
				{
					this.OnF10_OfficeST_VCChanging(value);
					this.SendPropertyChanging();
					this._F10_OfficeST_VC = value;
					this.SendPropertyChanged("F10_OfficeST_VC");
					this.OnF10_OfficeST_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F11_OfficeZip_VC", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string F11_OfficeZip_VC
		{
			get
			{
				return this._F11_OfficeZip_VC;
			}
			set
			{
				if ((this._F11_OfficeZip_VC != value))
				{
					this.OnF11_OfficeZip_VCChanging(value);
					this.SendPropertyChanging();
					this._F11_OfficeZip_VC = value;
					this.SendPropertyChanged("F11_OfficeZip_VC");
					this.OnF11_OfficeZip_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F12_OfficePhone_VC", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string F12_OfficePhone_VC
		{
			get
			{
				return this._F12_OfficePhone_VC;
			}
			set
			{
				if ((this._F12_OfficePhone_VC != value))
				{
					this.OnF12_OfficePhone_VCChanging(value);
					this.SendPropertyChanging();
					this._F12_OfficePhone_VC = value;
					this.SendPropertyChanged("F12_OfficePhone_VC");
					this.OnF12_OfficePhone_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F13_PatientAccountNumber_VC", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string F13_PatientAccountNumber_VC
		{
			get
			{
				return this._F13_PatientAccountNumber_VC;
			}
			set
			{
				if ((this._F13_PatientAccountNumber_VC != value))
				{
					this.OnF13_PatientAccountNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._F13_PatientAccountNumber_VC = value;
					this.SendPropertyChanged("F13_PatientAccountNumber_VC");
					this.OnF13_PatientAccountNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F14_StatementDate_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string F14_StatementDate_VC
		{
			get
			{
				return this._F14_StatementDate_VC;
			}
			set
			{
				if ((this._F14_StatementDate_VC != value))
				{
					this.OnF14_StatementDate_VCChanging(value);
					this.SendPropertyChanging();
					this._F14_StatementDate_VC = value;
					this.SendPropertyChanged("F14_StatementDate_VC");
					this.OnF14_StatementDate_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F15_PageNumber_VC", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string F15_PageNumber_VC
		{
			get
			{
				return this._F15_PageNumber_VC;
			}
			set
			{
				if ((this._F15_PageNumber_VC != value))
				{
					this.OnF15_PageNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._F15_PageNumber_VC = value;
					this.SendPropertyChanged("F15_PageNumber_VC");
					this.OnF15_PageNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F16_RemitToName_VC", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string F16_RemitToName_VC
		{
			get
			{
				return this._F16_RemitToName_VC;
			}
			set
			{
				if ((this._F16_RemitToName_VC != value))
				{
					this.OnF16_RemitToName_VCChanging(value);
					this.SendPropertyChanging();
					this._F16_RemitToName_VC = value;
					this.SendPropertyChanged("F16_RemitToName_VC");
					this.OnF16_RemitToName_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F17_RemitToAddress1_VC", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string F17_RemitToAddress1_VC
		{
			get
			{
				return this._F17_RemitToAddress1_VC;
			}
			set
			{
				if ((this._F17_RemitToAddress1_VC != value))
				{
					this.OnF17_RemitToAddress1_VCChanging(value);
					this.SendPropertyChanging();
					this._F17_RemitToAddress1_VC = value;
					this.SendPropertyChanged("F17_RemitToAddress1_VC");
					this.OnF17_RemitToAddress1_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F18_RemitToAddress2_VC", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string F18_RemitToAddress2_VC
		{
			get
			{
				return this._F18_RemitToAddress2_VC;
			}
			set
			{
				if ((this._F18_RemitToAddress2_VC != value))
				{
					this.OnF18_RemitToAddress2_VCChanging(value);
					this.SendPropertyChanging();
					this._F18_RemitToAddress2_VC = value;
					this.SendPropertyChanged("F18_RemitToAddress2_VC");
					this.OnF18_RemitToAddress2_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F19_RemitToCity_VC", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string F19_RemitToCity_VC
		{
			get
			{
				return this._F19_RemitToCity_VC;
			}
			set
			{
				if ((this._F19_RemitToCity_VC != value))
				{
					this.OnF19_RemitToCity_VCChanging(value);
					this.SendPropertyChanging();
					this._F19_RemitToCity_VC = value;
					this.SendPropertyChanged("F19_RemitToCity_VC");
					this.OnF19_RemitToCity_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F20_RemitToST_VC", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string F20_RemitToST_VC
		{
			get
			{
				return this._F20_RemitToST_VC;
			}
			set
			{
				if ((this._F20_RemitToST_VC != value))
				{
					this.OnF20_RemitToST_VCChanging(value);
					this.SendPropertyChanging();
					this._F20_RemitToST_VC = value;
					this.SendPropertyChanged("F20_RemitToST_VC");
					this.OnF20_RemitToST_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F21_RemitToZip_VC", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string F21_RemitToZip_VC
		{
			get
			{
				return this._F21_RemitToZip_VC;
			}
			set
			{
				if ((this._F21_RemitToZip_VC != value))
				{
					this.OnF21_RemitToZip_VCChanging(value);
					this.SendPropertyChanging();
					this._F21_RemitToZip_VC = value;
					this.SendPropertyChanged("F21_RemitToZip_VC");
					this.OnF21_RemitToZip_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F22_RemitToPhone_VC", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string F22_RemitToPhone_VC
		{
			get
			{
				return this._F22_RemitToPhone_VC;
			}
			set
			{
				if ((this._F22_RemitToPhone_VC != value))
				{
					this.OnF22_RemitToPhone_VCChanging(value);
					this.SendPropertyChanging();
					this._F22_RemitToPhone_VC = value;
					this.SendPropertyChanged("F22_RemitToPhone_VC");
					this.OnF22_RemitToPhone_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F23_RenderingProviderLastName_VC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string F23_RenderingProviderLastName_VC
		{
			get
			{
				return this._F23_RenderingProviderLastName_VC;
			}
			set
			{
				if ((this._F23_RenderingProviderLastName_VC != value))
				{
					this.OnF23_RenderingProviderLastName_VCChanging(value);
					this.SendPropertyChanging();
					this._F23_RenderingProviderLastName_VC = value;
					this.SendPropertyChanged("F23_RenderingProviderLastName_VC");
					this.OnF23_RenderingProviderLastName_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F23_RenderingProviderFirstName_VC", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string F23_RenderingProviderFirstName_VC
		{
			get
			{
				return this._F23_RenderingProviderFirstName_VC;
			}
			set
			{
				if ((this._F23_RenderingProviderFirstName_VC != value))
				{
					this.OnF23_RenderingProviderFirstName_VCChanging(value);
					this.SendPropertyChanging();
					this._F23_RenderingProviderFirstName_VC = value;
					this.SendPropertyChanged("F23_RenderingProviderFirstName_VC");
					this.OnF23_RenderingProviderFirstName_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F23_RenderingProviderMI_VC", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string F23_RenderingProviderMI_VC
		{
			get
			{
				return this._F23_RenderingProviderMI_VC;
			}
			set
			{
				if ((this._F23_RenderingProviderMI_VC != value))
				{
					this.OnF23_RenderingProviderMI_VCChanging(value);
					this.SendPropertyChanging();
					this._F23_RenderingProviderMI_VC = value;
					this.SendPropertyChanged("F23_RenderingProviderMI_VC");
					this.OnF23_RenderingProviderMI_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F24_RenderingProviderID_VC", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string F24_RenderingProviderID_VC
		{
			get
			{
				return this._F24_RenderingProviderID_VC;
			}
			set
			{
				if ((this._F24_RenderingProviderID_VC != value))
				{
					this.OnF24_RenderingProviderID_VCChanging(value);
					this.SendPropertyChanging();
					this._F24_RenderingProviderID_VC = value;
					this.SendPropertyChanged("F24_RenderingProviderID_VC");
					this.OnF24_RenderingProviderID_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F25_RenderingProviderST_VC", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string F25_RenderingProviderST_VC
		{
			get
			{
				return this._F25_RenderingProviderST_VC;
			}
			set
			{
				if ((this._F25_RenderingProviderST_VC != value))
				{
					this.OnF25_RenderingProviderST_VCChanging(value);
					this.SendPropertyChanging();
					this._F25_RenderingProviderST_VC = value;
					this.SendPropertyChanged("F25_RenderingProviderST_VC");
					this.OnF25_RenderingProviderST_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F26_PriorStatementDate_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string F26_PriorStatementDate_VC
		{
			get
			{
				return this._F26_PriorStatementDate_VC;
			}
			set
			{
				if ((this._F26_PriorStatementDate_VC != value))
				{
					this.OnF26_PriorStatementDate_VCChanging(value);
					this.SendPropertyChanging();
					this._F26_PriorStatementDate_VC = value;
					this.SendPropertyChanged("F26_PriorStatementDate_VC");
					this.OnF26_PriorStatementDate_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F27_PaymentDueDate_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string F27_PaymentDueDate_VC
		{
			get
			{
				return this._F27_PaymentDueDate_VC;
			}
			set
			{
				if ((this._F27_PaymentDueDate_VC != value))
				{
					this.OnF27_PaymentDueDate_VCChanging(value);
					this.SendPropertyChanging();
					this._F27_PaymentDueDate_VC = value;
					this.SendPropertyChanged("F27_PaymentDueDate_VC");
					this.OnF27_PaymentDueDate_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F28_PriorBalance_VC", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string F28_PriorBalance_VC
		{
			get
			{
				return this._F28_PriorBalance_VC;
			}
			set
			{
				if ((this._F28_PriorBalance_VC != value))
				{
					this.OnF28_PriorBalance_VCChanging(value);
					this.SendPropertyChanging();
					this._F28_PriorBalance_VC = value;
					this.SendPropertyChanged("F28_PriorBalance_VC");
					this.OnF28_PriorBalance_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F29_Adjustments_VC", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string F29_Adjustments_VC
		{
			get
			{
				return this._F29_Adjustments_VC;
			}
			set
			{
				if ((this._F29_Adjustments_VC != value))
				{
					this.OnF29_Adjustments_VCChanging(value);
					this.SendPropertyChanging();
					this._F29_Adjustments_VC = value;
					this.SendPropertyChanged("F29_Adjustments_VC");
					this.OnF29_Adjustments_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F30_BalanceDue_VC", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string F30_BalanceDue_VC
		{
			get
			{
				return this._F30_BalanceDue_VC;
			}
			set
			{
				if ((this._F30_BalanceDue_VC != value))
				{
					this.OnF30_BalanceDue_VCChanging(value);
					this.SendPropertyChanging();
					this._F30_BalanceDue_VC = value;
					this.SendPropertyChanged("F30_BalanceDue_VC");
					this.OnF30_BalanceDue_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F30B_AccountBalance_VC", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string F30B_AccountBalance_VC
		{
			get
			{
				return this._F30B_AccountBalance_VC;
			}
			set
			{
				if ((this._F30B_AccountBalance_VC != value))
				{
					this.OnF30B_AccountBalance_VCChanging(value);
					this.SendPropertyChanging();
					this._F30B_AccountBalance_VC = value;
					this.SendPropertyChanged("F30B_AccountBalance_VC");
					this.OnF30B_AccountBalance_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F31_FinanceCharge_VC", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string F31_FinanceCharge_VC
		{
			get
			{
				return this._F31_FinanceCharge_VC;
			}
			set
			{
				if ((this._F31_FinanceCharge_VC != value))
				{
					this.OnF31_FinanceCharge_VCChanging(value);
					this.SendPropertyChanging();
					this._F31_FinanceCharge_VC = value;
					this.SendPropertyChanged("F31_FinanceCharge_VC");
					this.OnF31_FinanceCharge_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F32_Credits_VC", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string F32_Credits_VC
		{
			get
			{
				return this._F32_Credits_VC;
			}
			set
			{
				if ((this._F32_Credits_VC != value))
				{
					this.OnF32_Credits_VCChanging(value);
					this.SendPropertyChanging();
					this._F32_Credits_VC = value;
					this.SendPropertyChanged("F32_Credits_VC");
					this.OnF32_Credits_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F33_EstimatedInsurancePayment_VC", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string F33_EstimatedInsurancePayment_VC
		{
			get
			{
				return this._F33_EstimatedInsurancePayment_VC;
			}
			set
			{
				if ((this._F33_EstimatedInsurancePayment_VC != value))
				{
					this.OnF33_EstimatedInsurancePayment_VCChanging(value);
					this.SendPropertyChanging();
					this._F33_EstimatedInsurancePayment_VC = value;
					this.SendPropertyChanged("F33_EstimatedInsurancePayment_VC");
					this.OnF33_EstimatedInsurancePayment_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F34_PatientShare_VC", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string F34_PatientShare_VC
		{
			get
			{
				return this._F34_PatientShare_VC;
			}
			set
			{
				if ((this._F34_PatientShare_VC != value))
				{
					this.OnF34_PatientShare_VCChanging(value);
					this.SendPropertyChanging();
					this._F34_PatientShare_VC = value;
					this.SendPropertyChanged("F34_PatientShare_VC");
					this.OnF34_PatientShare_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F35_CurrentBalance_VC", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string F35_CurrentBalance_VC
		{
			get
			{
				return this._F35_CurrentBalance_VC;
			}
			set
			{
				if ((this._F35_CurrentBalance_VC != value))
				{
					this.OnF35_CurrentBalance_VCChanging(value);
					this.SendPropertyChanging();
					this._F35_CurrentBalance_VC = value;
					this.SendPropertyChanged("F35_CurrentBalance_VC");
					this.OnF35_CurrentBalance_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F36_PastDue30_VC", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string F36_PastDue30_VC
		{
			get
			{
				return this._F36_PastDue30_VC;
			}
			set
			{
				if ((this._F36_PastDue30_VC != value))
				{
					this.OnF36_PastDue30_VCChanging(value);
					this.SendPropertyChanging();
					this._F36_PastDue30_VC = value;
					this.SendPropertyChanged("F36_PastDue30_VC");
					this.OnF36_PastDue30_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F37_PastDue60_VC", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string F37_PastDue60_VC
		{
			get
			{
				return this._F37_PastDue60_VC;
			}
			set
			{
				if ((this._F37_PastDue60_VC != value))
				{
					this.OnF37_PastDue60_VCChanging(value);
					this.SendPropertyChanging();
					this._F37_PastDue60_VC = value;
					this.SendPropertyChanged("F37_PastDue60_VC");
					this.OnF37_PastDue60_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F38_PastDue90_VC", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string F38_PastDue90_VC
		{
			get
			{
				return this._F38_PastDue90_VC;
			}
			set
			{
				if ((this._F38_PastDue90_VC != value))
				{
					this.OnF38_PastDue90_VCChanging(value);
					this.SendPropertyChanging();
					this._F38_PastDue90_VC = value;
					this.SendPropertyChanged("F38_PastDue90_VC");
					this.OnF38_PastDue90_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F39_PastDue120_VC", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string F39_PastDue120_VC
		{
			get
			{
				return this._F39_PastDue120_VC;
			}
			set
			{
				if ((this._F39_PastDue120_VC != value))
				{
					this.OnF39_PastDue120_VCChanging(value);
					this.SendPropertyChanging();
					this._F39_PastDue120_VC = value;
					this.SendPropertyChanged("F39_PastDue120_VC");
					this.OnF39_PastDue120_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TopNote_VC", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string TopNote_VC
		{
			get
			{
				return this._TopNote_VC;
			}
			set
			{
				if ((this._TopNote_VC != value))
				{
					this.OnTopNote_VCChanging(value);
					this.SendPropertyChanging();
					this._TopNote_VC = value;
					this.SendPropertyChanged("TopNote_VC");
					this.OnTopNote_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F40_Notes1_VC", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string F40_Notes1_VC
		{
			get
			{
				return this._F40_Notes1_VC;
			}
			set
			{
				if ((this._F40_Notes1_VC != value))
				{
					this.OnF40_Notes1_VCChanging(value);
					this.SendPropertyChanging();
					this._F40_Notes1_VC = value;
					this.SendPropertyChanged("F40_Notes1_VC");
					this.OnF40_Notes1_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F41_Notes2_VC", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string F41_Notes2_VC
		{
			get
			{
				return this._F41_Notes2_VC;
			}
			set
			{
				if ((this._F41_Notes2_VC != value))
				{
					this.OnF41_Notes2_VCChanging(value);
					this.SendPropertyChanging();
					this._F41_Notes2_VC = value;
					this.SendPropertyChanged("F41_Notes2_VC");
					this.OnF41_Notes2_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F42_Notes3_VC", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string F42_Notes3_VC
		{
			get
			{
				return this._F42_Notes3_VC;
			}
			set
			{
				if ((this._F42_Notes3_VC != value))
				{
					this.OnF42_Notes3_VCChanging(value);
					this.SendPropertyChanging();
					this._F42_Notes3_VC = value;
					this.SendPropertyChanged("F42_Notes3_VC");
					this.OnF42_Notes3_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F43_Notes4_VC", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string F43_Notes4_VC
		{
			get
			{
				return this._F43_Notes4_VC;
			}
			set
			{
				if ((this._F43_Notes4_VC != value))
				{
					this.OnF43_Notes4_VCChanging(value);
					this.SendPropertyChanging();
					this._F43_Notes4_VC = value;
					this.SendPropertyChanged("F43_Notes4_VC");
					this.OnF43_Notes4_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F44_Notes5_VC", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string F44_Notes5_VC
		{
			get
			{
				return this._F44_Notes5_VC;
			}
			set
			{
				if ((this._F44_Notes5_VC != value))
				{
					this.OnF44_Notes5_VCChanging(value);
					this.SendPropertyChanging();
					this._F44_Notes5_VC = value;
					this.SendPropertyChanged("F44_Notes5_VC");
					this.OnF44_Notes5_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F45_Notes6_VC", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string F45_Notes6_VC
		{
			get
			{
				return this._F45_Notes6_VC;
			}
			set
			{
				if ((this._F45_Notes6_VC != value))
				{
					this.OnF45_Notes6_VCChanging(value);
					this.SendPropertyChanging();
					this._F45_Notes6_VC = value;
					this.SendPropertyChanged("F45_Notes6_VC");
					this.OnF45_Notes6_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F46_Notes7_VC", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string F46_Notes7_VC
		{
			get
			{
				return this._F46_Notes7_VC;
			}
			set
			{
				if ((this._F46_Notes7_VC != value))
				{
					this.OnF46_Notes7_VCChanging(value);
					this.SendPropertyChanging();
					this._F46_Notes7_VC = value;
					this.SendPropertyChanged("F46_Notes7_VC");
					this.OnF46_Notes7_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F47_Notes8_VC", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string F47_Notes8_VC
		{
			get
			{
				return this._F47_Notes8_VC;
			}
			set
			{
				if ((this._F47_Notes8_VC != value))
				{
					this.OnF47_Notes8_VCChanging(value);
					this.SendPropertyChanging();
					this._F47_Notes8_VC = value;
					this.SendPropertyChanged("F47_Notes8_VC");
					this.OnF47_Notes8_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F48_Notes9_VC", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string F48_Notes9_VC
		{
			get
			{
				return this._F48_Notes9_VC;
			}
			set
			{
				if ((this._F48_Notes9_VC != value))
				{
					this.OnF48_Notes9_VCChanging(value);
					this.SendPropertyChanging();
					this._F48_Notes9_VC = value;
					this.SendPropertyChanged("F48_Notes9_VC");
					this.OnF48_Notes9_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F49_Notes10_VC", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string F49_Notes10_VC
		{
			get
			{
				return this._F49_Notes10_VC;
			}
			set
			{
				if ((this._F49_Notes10_VC != value))
				{
					this.OnF49_Notes10_VCChanging(value);
					this.SendPropertyChanging();
					this._F49_Notes10_VC = value;
					this.SendPropertyChanged("F49_Notes10_VC");
					this.OnF49_Notes10_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F00_StatementTitle_VC", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string F00_StatementTitle_VC
		{
			get
			{
				return this._F00_StatementTitle_VC;
			}
			set
			{
				if ((this._F00_StatementTitle_VC != value))
				{
					this.OnF00_StatementTitle_VCChanging(value);
					this.SendPropertyChanging();
					this._F00_StatementTitle_VC = value;
					this.SendPropertyChanged("F00_StatementTitle_VC");
					this.OnF00_StatementTitle_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F50_PendingAtInsurance_VC", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string F50_PendingAtInsurance_VC
		{
			get
			{
				return this._F50_PendingAtInsurance_VC;
			}
			set
			{
				if ((this._F50_PendingAtInsurance_VC != value))
				{
					this.OnF50_PendingAtInsurance_VCChanging(value);
					this.SendPropertyChanging();
					this._F50_PendingAtInsurance_VC = value;
					this.SendPropertyChanged("F50_PendingAtInsurance_VC");
					this.OnF50_PendingAtInsurance_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceDate_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string ServiceDate_VC
		{
			get
			{
				return this._ServiceDate_VC;
			}
			set
			{
				if ((this._ServiceDate_VC != value))
				{
					this.OnServiceDate_VCChanging(value);
					this.SendPropertyChanging();
					this._ServiceDate_VC = value;
					this.SendPropertyChanged("ServiceDate_VC");
					this.OnServiceDate_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UniqueNameOnClaim_VC", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string UniqueNameOnClaim_VC
		{
			get
			{
				return this._UniqueNameOnClaim_VC;
			}
			set
			{
				if ((this._UniqueNameOnClaim_VC != value))
				{
					this.OnUniqueNameOnClaim_VCChanging(value);
					this.SendPropertyChanging();
					this._UniqueNameOnClaim_VC = value;
					this.SendPropertyChanged("UniqueNameOnClaim_VC");
					this.OnUniqueNameOnClaim_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vendor_ID", DbType="Int")]
		public System.Nullable<int> Vendor_ID
		{
			get
			{
				return this._Vendor_ID;
			}
			set
			{
				if ((this._Vendor_ID != value))
				{
					this.OnVendor_IDChanging(value);
					this.SendPropertyChanging();
					this._Vendor_ID = value;
					this.SendPropertyChanged("Vendor_ID");
					this.OnVendor_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalDocumentPageCount", DbType="Int")]
		public System.Nullable<int> OriginalDocumentPageCount
		{
			get
			{
				return this._OriginalDocumentPageCount;
			}
			set
			{
				if ((this._OriginalDocumentPageCount != value))
				{
					this.OnOriginalDocumentPageCountChanging(value);
					this.SendPropertyChanging();
					this._OriginalDocumentPageCount = value;
					this.SendPropertyChanged("OriginalDocumentPageCount");
					this.OnOriginalDocumentPageCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalDocumentName", DbType="NVarChar(260)")]
		public string OriginalDocumentName
		{
			get
			{
				return this._OriginalDocumentName;
			}
			set
			{
				if ((this._OriginalDocumentName != value))
				{
					this.OnOriginalDocumentNameChanging(value);
					this.SendPropertyChanging();
					this._OriginalDocumentName = value;
					this.SendPropertyChanged("OriginalDocumentName");
					this.OnOriginalDocumentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RenderingProviderNameSuffix", DbType="NVarChar(20)")]
		public string RenderingProviderNameSuffix
		{
			get
			{
				return this._RenderingProviderNameSuffix;
			}
			set
			{
				if ((this._RenderingProviderNameSuffix != value))
				{
					this.OnRenderingProviderNameSuffixChanging(value);
					this.SendPropertyChanging();
					this._RenderingProviderNameSuffix = value;
					this.SendPropertyChanged("RenderingProviderNameSuffix");
					this.OnRenderingProviderNameSuffixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingContactFirstName", DbType="NVarChar(50)")]
		public string BillingContactFirstName
		{
			get
			{
				return this._BillingContactFirstName;
			}
			set
			{
				if ((this._BillingContactFirstName != value))
				{
					this.OnBillingContactFirstNameChanging(value);
					this.SendPropertyChanging();
					this._BillingContactFirstName = value;
					this.SendPropertyChanged("BillingContactFirstName");
					this.OnBillingContactFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingContactMiddleName", DbType="NVarChar(50)")]
		public string BillingContactMiddleName
		{
			get
			{
				return this._BillingContactMiddleName;
			}
			set
			{
				if ((this._BillingContactMiddleName != value))
				{
					this.OnBillingContactMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._BillingContactMiddleName = value;
					this.SendPropertyChanged("BillingContactMiddleName");
					this.OnBillingContactMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingContactLastName", DbType="NVarChar(50)")]
		public string BillingContactLastName
		{
			get
			{
				return this._BillingContactLastName;
			}
			set
			{
				if ((this._BillingContactLastName != value))
				{
					this.OnBillingContactLastNameChanging(value);
					this.SendPropertyChanging();
					this._BillingContactLastName = value;
					this.SendPropertyChanged("BillingContactLastName");
					this.OnBillingContactLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingContactSuffix", DbType="NVarChar(20)")]
		public string BillingContactSuffix
		{
			get
			{
				return this._BillingContactSuffix;
			}
			set
			{
				if ((this._BillingContactSuffix != value))
				{
					this.OnBillingContactSuffixChanging(value);
					this.SendPropertyChanging();
					this._BillingContactSuffix = value;
					this.SendPropertyChanged("BillingContactSuffix");
					this.OnBillingContactSuffixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipientNameSuffix", DbType="NVarChar(20)")]
		public string RecipientNameSuffix
		{
			get
			{
				return this._RecipientNameSuffix;
			}
			set
			{
				if ((this._RecipientNameSuffix != value))
				{
					this.OnRecipientNameSuffixChanging(value);
					this.SendPropertyChanging();
					this._RecipientNameSuffix = value;
					this.SendPropertyChanged("RecipientNameSuffix");
					this.OnRecipientNameSuffixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientNameSuffix", DbType="NVarChar(20)")]
		public string PatientNameSuffix
		{
			get
			{
				return this._PatientNameSuffix;
			}
			set
			{
				if ((this._PatientNameSuffix != value))
				{
					this.OnPatientNameSuffixChanging(value);
					this.SendPropertyChanging();
					this._PatientNameSuffix = value;
					this.SendPropertyChanged("PatientNameSuffix");
					this.OnPatientNameSuffixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentSource", DbType="Int")]
		public System.Nullable<int> DocumentSource
		{
			get
			{
				return this._DocumentSource;
			}
			set
			{
				if ((this._DocumentSource != value))
				{
					this.OnDocumentSourceChanging(value);
					this.SendPropertyChanging();
					this._DocumentSource = value;
					this.SendPropertyChanged("DocumentSource");
					this.OnDocumentSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Statement_T_StatementLineItem_T", Storage="_StatementLineItem_Ts", ThisKey="Claim_ID", OtherKey="Claim_ID")]
		public EntitySet<StatementLineItem_T> StatementLineItem_Ts
		{
			get
			{
				return this._StatementLineItem_Ts;
			}
			set
			{
				this._StatementLineItem_Ts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StatementLineItem_Ts(StatementLineItem_T entity)
		{
			this.SendPropertyChanging();
			entity.Statement_T = this;
		}
		
		private void detach_StatementLineItem_Ts(StatementLineItem_T entity)
		{
			this.SendPropertyChanging();
			entity.Statement_T = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StatementLineItem_T")]
	public partial class StatementLineItem_T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _StatementLineItem_ID;
		
		private long _Claim_ID;
		
		private long _Parent_ID;
		
		private System.Nullable<int> _LineItemNumber_TI;
		
		private string _ServiceDate_VC;
		
		private string _ToothNumber_VC;
		
		private string _ToothSurface_VC;
		
		private string _DescriptionOfServices_VC;
		
		private string _PatientName_VC;
		
		private string _Charges_VC;
		
		private string _Credits_VC;
		
		private string _InsuranceBilled_VC;
		
		private string _UnitsOrdered_VC;
		
		private string _QuantityProvided_VC;
		
		private string _UnitPrice_VC;
		
		private string _ReferenceNumber_VC;
		
		private string _ProcedureCode_VC;
		
		private string _Error_VC;
		
		private string _InsurancePaid_VC;
		
		private string _Other_VC;
		
		private string _PatientAmount_VC;
		
		private string _InsuranceAdjustment_VC;
		
		private string _PatientAdjustment_VC;
		
		private string _TransactionDate_VC;
		
		private string _BalanceAmount_VC;
		
		private EntityRef<Statement_T> _Statement_T;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStatementLineItem_IDChanging(long value);
    partial void OnStatementLineItem_IDChanged();
    partial void OnClaim_IDChanging(long value);
    partial void OnClaim_IDChanged();
    partial void OnParent_IDChanging(long value);
    partial void OnParent_IDChanged();
    partial void OnLineItemNumber_TIChanging(System.Nullable<int> value);
    partial void OnLineItemNumber_TIChanged();
    partial void OnServiceDate_VCChanging(string value);
    partial void OnServiceDate_VCChanged();
    partial void OnToothNumber_VCChanging(string value);
    partial void OnToothNumber_VCChanged();
    partial void OnToothSurface_VCChanging(string value);
    partial void OnToothSurface_VCChanged();
    partial void OnDescriptionOfServices_VCChanging(string value);
    partial void OnDescriptionOfServices_VCChanged();
    partial void OnPatientName_VCChanging(string value);
    partial void OnPatientName_VCChanged();
    partial void OnCharges_VCChanging(string value);
    partial void OnCharges_VCChanged();
    partial void OnCredits_VCChanging(string value);
    partial void OnCredits_VCChanged();
    partial void OnInsuranceBilled_VCChanging(string value);
    partial void OnInsuranceBilled_VCChanged();
    partial void OnUnitsOrdered_VCChanging(string value);
    partial void OnUnitsOrdered_VCChanged();
    partial void OnQuantityProvided_VCChanging(string value);
    partial void OnQuantityProvided_VCChanged();
    partial void OnUnitPrice_VCChanging(string value);
    partial void OnUnitPrice_VCChanged();
    partial void OnReferenceNumber_VCChanging(string value);
    partial void OnReferenceNumber_VCChanged();
    partial void OnProcedureCode_VCChanging(string value);
    partial void OnProcedureCode_VCChanged();
    partial void OnError_VCChanging(string value);
    partial void OnError_VCChanged();
    partial void OnInsurancePaid_VCChanging(string value);
    partial void OnInsurancePaid_VCChanged();
    partial void OnOther_VCChanging(string value);
    partial void OnOther_VCChanged();
    partial void OnPatientAmount_VCChanging(string value);
    partial void OnPatientAmount_VCChanged();
    partial void OnInsuranceAdjustment_VCChanging(string value);
    partial void OnInsuranceAdjustment_VCChanged();
    partial void OnPatientAdjustment_VCChanging(string value);
    partial void OnPatientAdjustment_VCChanged();
    partial void OnTransactionDate_VCChanging(string value);
    partial void OnTransactionDate_VCChanged();
    partial void OnBalanceAmount_VCChanging(string value);
    partial void OnBalanceAmount_VCChanged();
    #endregion
		
		public StatementLineItem_T()
		{
			this._Statement_T = default(EntityRef<Statement_T>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatementLineItem_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long StatementLineItem_ID
		{
			get
			{
				return this._StatementLineItem_ID;
			}
			set
			{
				if ((this._StatementLineItem_ID != value))
				{
					this.OnStatementLineItem_IDChanging(value);
					this.SendPropertyChanging();
					this._StatementLineItem_ID = value;
					this.SendPropertyChanged("StatementLineItem_ID");
					this.OnStatementLineItem_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Claim_ID", DbType="BigInt NOT NULL")]
		public long Claim_ID
		{
			get
			{
				return this._Claim_ID;
			}
			set
			{
				if ((this._Claim_ID != value))
				{
					if (this._Statement_T.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClaim_IDChanging(value);
					this.SendPropertyChanging();
					this._Claim_ID = value;
					this.SendPropertyChanged("Claim_ID");
					this.OnClaim_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent_ID", DbType="BigInt NOT NULL")]
		public long Parent_ID
		{
			get
			{
				return this._Parent_ID;
			}
			set
			{
				if ((this._Parent_ID != value))
				{
					this.OnParent_IDChanging(value);
					this.SendPropertyChanging();
					this._Parent_ID = value;
					this.SendPropertyChanged("Parent_ID");
					this.OnParent_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineItemNumber_TI", DbType="Int")]
		public System.Nullable<int> LineItemNumber_TI
		{
			get
			{
				return this._LineItemNumber_TI;
			}
			set
			{
				if ((this._LineItemNumber_TI != value))
				{
					this.OnLineItemNumber_TIChanging(value);
					this.SendPropertyChanging();
					this._LineItemNumber_TI = value;
					this.SendPropertyChanged("LineItemNumber_TI");
					this.OnLineItemNumber_TIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceDate_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string ServiceDate_VC
		{
			get
			{
				return this._ServiceDate_VC;
			}
			set
			{
				if ((this._ServiceDate_VC != value))
				{
					this.OnServiceDate_VCChanging(value);
					this.SendPropertyChanging();
					this._ServiceDate_VC = value;
					this.SendPropertyChanged("ServiceDate_VC");
					this.OnServiceDate_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToothNumber_VC", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ToothNumber_VC
		{
			get
			{
				return this._ToothNumber_VC;
			}
			set
			{
				if ((this._ToothNumber_VC != value))
				{
					this.OnToothNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._ToothNumber_VC = value;
					this.SendPropertyChanged("ToothNumber_VC");
					this.OnToothNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToothSurface_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string ToothSurface_VC
		{
			get
			{
				return this._ToothSurface_VC;
			}
			set
			{
				if ((this._ToothSurface_VC != value))
				{
					this.OnToothSurface_VCChanging(value);
					this.SendPropertyChanging();
					this._ToothSurface_VC = value;
					this.SendPropertyChanged("ToothSurface_VC");
					this.OnToothSurface_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescriptionOfServices_VC", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string DescriptionOfServices_VC
		{
			get
			{
				return this._DescriptionOfServices_VC;
			}
			set
			{
				if ((this._DescriptionOfServices_VC != value))
				{
					this.OnDescriptionOfServices_VCChanging(value);
					this.SendPropertyChanging();
					this._DescriptionOfServices_VC = value;
					this.SendPropertyChanged("DescriptionOfServices_VC");
					this.OnDescriptionOfServices_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientName_VC", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PatientName_VC
		{
			get
			{
				return this._PatientName_VC;
			}
			set
			{
				if ((this._PatientName_VC != value))
				{
					this.OnPatientName_VCChanging(value);
					this.SendPropertyChanging();
					this._PatientName_VC = value;
					this.SendPropertyChanged("PatientName_VC");
					this.OnPatientName_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Charges_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Charges_VC
		{
			get
			{
				return this._Charges_VC;
			}
			set
			{
				if ((this._Charges_VC != value))
				{
					this.OnCharges_VCChanging(value);
					this.SendPropertyChanging();
					this._Charges_VC = value;
					this.SendPropertyChanged("Charges_VC");
					this.OnCharges_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Credits_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Credits_VC
		{
			get
			{
				return this._Credits_VC;
			}
			set
			{
				if ((this._Credits_VC != value))
				{
					this.OnCredits_VCChanging(value);
					this.SendPropertyChanging();
					this._Credits_VC = value;
					this.SendPropertyChanged("Credits_VC");
					this.OnCredits_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsuranceBilled_VC", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string InsuranceBilled_VC
		{
			get
			{
				return this._InsuranceBilled_VC;
			}
			set
			{
				if ((this._InsuranceBilled_VC != value))
				{
					this.OnInsuranceBilled_VCChanging(value);
					this.SendPropertyChanging();
					this._InsuranceBilled_VC = value;
					this.SendPropertyChanged("InsuranceBilled_VC");
					this.OnInsuranceBilled_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitsOrdered_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string UnitsOrdered_VC
		{
			get
			{
				return this._UnitsOrdered_VC;
			}
			set
			{
				if ((this._UnitsOrdered_VC != value))
				{
					this.OnUnitsOrdered_VCChanging(value);
					this.SendPropertyChanging();
					this._UnitsOrdered_VC = value;
					this.SendPropertyChanged("UnitsOrdered_VC");
					this.OnUnitsOrdered_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuantityProvided_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string QuantityProvided_VC
		{
			get
			{
				return this._QuantityProvided_VC;
			}
			set
			{
				if ((this._QuantityProvided_VC != value))
				{
					this.OnQuantityProvided_VCChanging(value);
					this.SendPropertyChanging();
					this._QuantityProvided_VC = value;
					this.SendPropertyChanged("QuantityProvided_VC");
					this.OnQuantityProvided_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitPrice_VC", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string UnitPrice_VC
		{
			get
			{
				return this._UnitPrice_VC;
			}
			set
			{
				if ((this._UnitPrice_VC != value))
				{
					this.OnUnitPrice_VCChanging(value);
					this.SendPropertyChanging();
					this._UnitPrice_VC = value;
					this.SendPropertyChanged("UnitPrice_VC");
					this.OnUnitPrice_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceNumber_VC", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ReferenceNumber_VC
		{
			get
			{
				return this._ReferenceNumber_VC;
			}
			set
			{
				if ((this._ReferenceNumber_VC != value))
				{
					this.OnReferenceNumber_VCChanging(value);
					this.SendPropertyChanging();
					this._ReferenceNumber_VC = value;
					this.SendPropertyChanged("ReferenceNumber_VC");
					this.OnReferenceNumber_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcedureCode_VC", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string ProcedureCode_VC
		{
			get
			{
				return this._ProcedureCode_VC;
			}
			set
			{
				if ((this._ProcedureCode_VC != value))
				{
					this.OnProcedureCode_VCChanging(value);
					this.SendPropertyChanging();
					this._ProcedureCode_VC = value;
					this.SendPropertyChanged("ProcedureCode_VC");
					this.OnProcedureCode_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error_VC", DbType="VarChar(20)")]
		public string Error_VC
		{
			get
			{
				return this._Error_VC;
			}
			set
			{
				if ((this._Error_VC != value))
				{
					this.OnError_VCChanging(value);
					this.SendPropertyChanging();
					this._Error_VC = value;
					this.SendPropertyChanged("Error_VC");
					this.OnError_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsurancePaid_VC", DbType="VarChar(10)")]
		public string InsurancePaid_VC
		{
			get
			{
				return this._InsurancePaid_VC;
			}
			set
			{
				if ((this._InsurancePaid_VC != value))
				{
					this.OnInsurancePaid_VCChanging(value);
					this.SendPropertyChanging();
					this._InsurancePaid_VC = value;
					this.SendPropertyChanged("InsurancePaid_VC");
					this.OnInsurancePaid_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other_VC", DbType="VarChar(30)")]
		public string Other_VC
		{
			get
			{
				return this._Other_VC;
			}
			set
			{
				if ((this._Other_VC != value))
				{
					this.OnOther_VCChanging(value);
					this.SendPropertyChanging();
					this._Other_VC = value;
					this.SendPropertyChanged("Other_VC");
					this.OnOther_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAmount_VC", DbType="VarChar(10)")]
		public string PatientAmount_VC
		{
			get
			{
				return this._PatientAmount_VC;
			}
			set
			{
				if ((this._PatientAmount_VC != value))
				{
					this.OnPatientAmount_VCChanging(value);
					this.SendPropertyChanging();
					this._PatientAmount_VC = value;
					this.SendPropertyChanged("PatientAmount_VC");
					this.OnPatientAmount_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsuranceAdjustment_VC", DbType="VarChar(10)")]
		public string InsuranceAdjustment_VC
		{
			get
			{
				return this._InsuranceAdjustment_VC;
			}
			set
			{
				if ((this._InsuranceAdjustment_VC != value))
				{
					this.OnInsuranceAdjustment_VCChanging(value);
					this.SendPropertyChanging();
					this._InsuranceAdjustment_VC = value;
					this.SendPropertyChanged("InsuranceAdjustment_VC");
					this.OnInsuranceAdjustment_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAdjustment_VC", DbType="VarChar(10)")]
		public string PatientAdjustment_VC
		{
			get
			{
				return this._PatientAdjustment_VC;
			}
			set
			{
				if ((this._PatientAdjustment_VC != value))
				{
					this.OnPatientAdjustment_VCChanging(value);
					this.SendPropertyChanging();
					this._PatientAdjustment_VC = value;
					this.SendPropertyChanged("PatientAdjustment_VC");
					this.OnPatientAdjustment_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionDate_VC", DbType="VarChar(8)")]
		public string TransactionDate_VC
		{
			get
			{
				return this._TransactionDate_VC;
			}
			set
			{
				if ((this._TransactionDate_VC != value))
				{
					this.OnTransactionDate_VCChanging(value);
					this.SendPropertyChanging();
					this._TransactionDate_VC = value;
					this.SendPropertyChanged("TransactionDate_VC");
					this.OnTransactionDate_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BalanceAmount_VC", DbType="VarChar(10)")]
		public string BalanceAmount_VC
		{
			get
			{
				return this._BalanceAmount_VC;
			}
			set
			{
				if ((this._BalanceAmount_VC != value))
				{
					this.OnBalanceAmount_VCChanging(value);
					this.SendPropertyChanging();
					this._BalanceAmount_VC = value;
					this.SendPropertyChanged("BalanceAmount_VC");
					this.OnBalanceAmount_VCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Statement_T_StatementLineItem_T", Storage="_Statement_T", ThisKey="Claim_ID", OtherKey="Claim_ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Statement_T Statement_T
		{
			get
			{
				return this._Statement_T.Entity;
			}
			set
			{
				Statement_T previousValue = this._Statement_T.Entity;
				if (((previousValue != value) 
							|| (this._Statement_T.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Statement_T.Entity = null;
						previousValue.StatementLineItem_Ts.Remove(this);
					}
					this._Statement_T.Entity = value;
					if ((value != null))
					{
						value.StatementLineItem_Ts.Add(this);
						this._Claim_ID = value.Claim_ID;
					}
					else
					{
						this._Claim_ID = default(long);
					}
					this.SendPropertyChanged("Statement_T");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
